# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4bda8cfef29a22e8f0ad6ecdbd2e2480d65dded16401ebce683cbce4f9b3ca884f4f368a842a4278615f5b980ba75d1b18e017f7724f4ddda18280b61a086d16

test:
  secret_key_base: 82e7fd769ca247b3eda61cb57114883ab630cd9bed0049df1d782d040667e21c4a968d42feddb208c82b9ad127f2ca955ba833f50d7c4d9688a322a039a0722f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
